
version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - 5672:5672
      - 15672:15672

    networks:
      - network

  consumer:
    build: .

    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RMQ_URL: 'amqp://guest:guest@localhost:5672/'
      RMQ_EXCANGE: 'services'
      RMQ_QUEUE: 'fms_agreement_in'
      RUCAPTCHA_TOKEN: ''
      LOG_PATH: 'debug.log'

    depends_on:
      - rabbitmq

    networks:
      - network

networks:
  network: {}